image: debian

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build:
    stage: build
    script:
        - mkdir bin

        - make

        - cp -R medusa_software/libmedusa/bin/libmedusa.so bin/
    artifacts:
        untracked: false
        expire_in: "30 days"
        paths:
            - bin
