all:
    script:
        - echo "Hello, world!"
        - uname -a > example.txt
        - hostname >> example.txt
    artifacts:
      untracked: false
      expire_in: "30 days"
      paths:
        - example.txt