image: debian

before_script:
    - tools/deps_debian.sh
    - git submodule init
    - git submodule update

all:
    script:
        - echo "Hello, world!"
        - clang++
    artifacts:
        untracked: false
        expire_in: "30 days"