#!/bin/bash
#
#  Copyright (C) 2022, w212 research. <contact@w212research.com>
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of version 2 of the GNU General Public License as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

if [ -e .commit_in_progress ]; then
	rm .commit_in_progress

	# ensure MEDUSA_PATH is set
	export MEDUSA_PATH=$(realpath $(dirname $(realpath $0))/../..)

	$MEDUSA_PATH/tools/badges/badges.sh
	git add $MEDUSA_PATH/res/badges

	cd $MEDUSA_PATH/wiki
	git pull origin HEAD:master
	cd $MEDUSA_PATH
	git add wiki

	git commit --amend -c HEAD --no-verify
fi

exit
